AppBundle\Entity\Dietary:
    type: entity
    table: dietary
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        wording:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        img:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
    oneToMany:
         menuitems:
             targetEntity: Menuitem
             mappedBy: dietary
    lifecycleCallbacks: {  }
