AppBundle\Entity\Foodcourt:
    type: entity
    table: foodcourt
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        place:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        lat:
            type: integer
            nullable: true
            options:
                unsigned: false
        lng:
            type: integer
            nullable: true
            options:
                unsigned: false
        img:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        seatingcapacity:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: seatingCapacity
    oneToMany:
        foodstalls:
            targetEntity: Foodstall
            mappedBy: foodcourt
    lifecycleCallbacks: {  }
