AppBundle\Entity\FoodstallCategory:
    type: entity
    table: foodstall_category
    indexes:
        FK_foodStall_foodStall:
            columns:
                - foodStallId
        FK_foodStall_category:
            columns:
                - categoryId
    id:
        foodstallid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: foodStallId
        categoryid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: categoryId
    lifecycleCallbacks: {  }
