AppBundle\Entity\Foodstall:
    type: entity
    table: foodstall
    indexes:
        FK_foodStall_foodCourt:
            columns:
                - foodCourtId
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        img:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    oneToMany:
        categories:
            targetEntity: FoodstallCategory
            mappedBy: foodstall
        menuitems:
            targetEntity: Menuitem
            mappedBy: foodstall
    manyToOne:
        foodcourt:
            targetEntity: Foodcourt
            inversedBy: foodstalls
            joinColumn:
                name: foodCourtId
                referencedColumnName: id
    lifecycleCallbacks: {  }
