AppBundle\Entity\Review:
    type: entity
    table: review
    indexes:
        FK_review_foodCourt:
            columns:
                - foodCourtId
        FK_review_foodStall:
            columns:
                - foodStallId
        FK_review_user:
            columns:
                - userId
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rating:
            type: integer
            nullable: false
            options:
                unsigned: false
        content:
            type: integer
            nullable: true
            options:
                unsigned: false
        datecreated:
            type: date
            nullable: false
            column: dateCreated
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: userId
        foodstallid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: foodStallId
        foodcourtid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: foodCourtId
    lifecycleCallbacks: {  }
